// src/types/supabase.ts
// Generated by Supabase CLI — do not edit manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      roles: {
        Row: {
          id: number
          slug: string
          name: string
          track: 'tech' | 'bluecollar'
          description: string | null
          sort_order: number
        }
        Insert: {
          id?: number
          slug: string
          name: string
          track: 'tech' | 'bluecollar'
          description?: string | null
          sort_order?: number
        }
        Update: {
          id?: number
          slug?: string
          name?: string
          track?: 'tech' | 'bluecollar'
          description?: string | null
          sort_order?: number
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          user_id: string
          role_id: number
          is_primary: boolean
          created_at: string
        }
        Insert: {
          user_id: string
          role_id: number
          is_primary?: boolean
          created_at?: string
        }
        Update: {
          user_id?: string
          role_id?: number
          is_primary?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_roles_role_id_fkey"
            columns: ["role_id"]
            referencedRelation: "roles"
            referencedColumns: ["id"]
          }
        ]
      }
      onboarding_responses: {
        Row: {
          id: number
          user_id: string
          question_slug: string
          answer_text: string | null
          answer_int: number | null
          answer_boolean: boolean | null
          created_at: string
        }
        Insert: {
          id?: number
          user_id: string
          question_slug: string
          answer_text?: string | null
          answer_int?: number | null
          answer_boolean?: boolean | null
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          question_slug?: string
          answer_text?: string | null
          answer_int?: number | null
          answer_boolean?: boolean | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_responses_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
    CompositeTypes: {}
  }
}